name: Build

on: [push, pull_request]

jobs:
  build_ubuntu:
    name: Verify compilation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y meson libimlib2-dev
      - run: meson setup -Dwarning_level=3 build
      - run: ninja -C build
